import type { Browser } from "playwright";
import { Octokit } from "@octokit/rest";
import type { ContentFix, Finding } from "../types.js";
import { env, monitorConfig } from "../config.js";

/**
 * Verifies configured copy/HTML replacements on live pages.
 * When WEBSITE_REPO_* is set and CONTENT_FIXES_ENABLED=true,
 * opens a GitHub issue with the suggested diff (WP theme edits are manual).
 */
export async function runContentFixChecks(
  browser: Browser,
): Promise<{
  results: { id: string; applied: boolean; message: string }[];
  findings: Finding[];
}> {
  const fixes = monitorConfig.contentFixes.filter((f) => f.enabled);
  const results: { id: string; applied: boolean; message: string }[] = [];
  const findings: Finding[] = [];

  if (fixes.length === 0) {
    return { results, findings };
  }

  const context = await browser.newContext();
  const page = await context.newPage();

  for (const fix of fixes) {
    try {
      await page.goto(fix.pageUrl, {
        waitUntil: "domcontentloaded",
        timeout: 45_000,
      });
      const html = await page.locator(fix.selector).first().innerHTML().catch(() => "");
      const text = await page.locator(fix.selector).first().innerText().catch(() => "");

      const hasFind = html.includes(fix.find) || text.includes(fix.find);
      if (hasFind) {
        results.push({
          id: fix.id,
          applied: false,
          message: `Still contains outdated copy: "${fix.find.slice(0, 60)}..."`,
        });
        findings.push({
          id: `content-fix-${fix.id}`,
          severity: "info",
          category: "content",
          title: `Content fix pending: ${fix.description}`,
          detail: `Replace "${fix.find}" → "${fix.replace}" on ${fix.pageUrl}`,
          url: fix.pageUrl,
        });

        if (env.CONTENT_FIXES_ENABLED && env.GITHUB_TOKEN) {
          await fileContentFixIssue(fix);
        }
      } else if (text.includes(fix.replace) || html.includes(fix.replace)) {
        results.push({
          id: fix.id,
          applied: true,
          message: "Replacement text present",
        });
      } else {
        results.push({
          id: fix.id,
          applied: false,
          message: "Neither old nor new copy found — verify selector",
        });
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      results.push({ id: fix.id, applied: false, message });
    }
  }

  await context.close();
  return { results, findings };
}

async function fileContentFixIssue(fix: ContentFix): Promise<void> {
  const octokit = new Octokit({ auth: env.GITHUB_TOKEN });
  const title = `[content] ${fix.description}`;
  const body = [
    "## Suggested copy update",
    "",
    `- **Page:** ${fix.pageUrl}`,
    `- **Selector:** \`${fix.selector}\``,
    "",
    "### Change",
    "",
    "```diff",
    `- ${fix.find}`,
    `+ ${fix.replace}`,
    "```",
    "",
    "_Auto-generated by Iris ID monitoring agent._",
  ].join("\n");

  const existing = await octokit.paginate(octokit.rest.issues.listForRepo, {
    owner: env.GITHUB_OWNER,
    repo: env.GITHUB_REPO,
    state: "open",
    per_page: 100,
  });

  if (existing.some((i) => i.title === title)) return;

  await octokit.rest.issues.create({
    owner: env.GITHUB_OWNER,
    repo: env.GITHUB_REPO,
    title,
    body,
    labels: ["content", "monitoring"],
  });
}
